# root-sync.yaml to demo setting up the config sync product on cloud resource accelerator 
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: resource-accelerator
  namespace: config-management-system
spec:
  sourceType: git
  sourceFormat: hierarchy
  git:
    repo: https://github.com/FrankelJb/cloud-resource-accelerator
    auth: none
    dir: config-sync
    branch: main
