apiVersion: gkehub.gcp.gke.cloud.google.com/v1beta1
kind: Membership
metadata:
  labels:
    testing.anthos/name: membership
  name: membership
spec:
  forProvider:
    endpoint:
      - gkeCluster:
          - resourceLinkSelector:
              matchLabels:
                crossplane.io/claim-namespace: google