apiVersion:  eks.aws.gke.cloud.google.com/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/external-name: eks-cluster # name of cluster
  name: eks-cluster # name of cluster
spec:
#   providerConfigRef: 
#     name: default-aws # edit to match provider config if not default
  forProvider:
    region: us-east-1
    roleArn: arn:aws:iam::389906835311:role/anthos-role
    version: "1.25"
    vpcConfig:
      - subnetIds:
        - subnet-0566150d65fd1fc60
        - subnet-072b99f2939e57942
        - subnet-0c0078044dbeb14fb
