apiVersion: azure.gke.cloud.google.com/v1beta1
kind: ProviderConfig
metadata:
  name: default-azure
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-creds
      key: creds
