#Example of importing an AKS cluster into a composition 
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: import-azure-aks
  labels:
    crossplane.io/xrd: compositeclusters.demo.anthos.com
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeCluster
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: cluster
    base:
      apiVersion: containerservice.azure.gke.cloud.google.com/v1beta1
      kind: KubernetesCluster
      metadata:
        annotations:
          crossplane.io/external-name: aks-cluster 
      spec:
        writeConnectionSecretToRef:
          namespace: default
        forProvider:
          defaultNodePool:
            - name: default
            #  nodeCount: 1
              vmSize: Standard_B2s
          dnsPrefix: akscluster
          identity:
            - type: SystemAssigned
           # - type: UserAssigned
          #kubernetesVersion: 1.26
          location: "East Us"
          resourceGroupName: rg
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.managementPolicy
      toFieldPath: spec.managementPolicy
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.dnsPrefix
      toFieldPath: spec.forProvider.dnsPrefix
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.defaultNodePoolName
      toFieldPath: spec.forProvider.defaultNodePool[0].name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.vmSize
      toFieldPath: spec.forProvider.defaultNodePool[0].vmSize 
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.resourceGroup
      toFieldPath: spec.forProvider.resourceGroupName
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.clusterName
    - type: ToCompositeFieldPath
      fromFieldPath: spec.forProvider.location
      toFieldPath: status.region
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.oidcIssuerUrl
      toFieldPath: status.odicIssuerUrl
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-akscluster"

  - name: clusterbootstrap
    base:
      apiVersion: containerattached.gcp.gke.cloud.google.com/v1beta1
      kind: ClusterBootstrapJob
      metadata:
        name: installmanifest
        labels:
          name: attachedclusterbootstrap
      spec:
        forProvider:
          clusterConfig:
            project: ""
            id: ""
            location: us-east4
            platformVersion: "aks"
          clusterCredentials:
            source: Secret
            secretRef:
              namespace: default
              key: kubeconfig
    patches:
    - fromFieldPath: spec.parameters.k8sVersion
      toFieldPath: spec.forProvider.clusterConfig.platformVersion
      transforms:
      - type: map
        map:
          1.24: 1.24.0-gke.4
          1.25: 1.25.0-gke.4
          1.26: 1.26.0-gke.2
    - fromFieldPath: spec.parameters.clusterName
      toFieldPath: spec.forProvider.clusterConfig.id
    - fromFieldPath: spec.parameters.anthosGCPRegion
      toFieldPath: spec.forProvider.clusterConfig.location
    - fromFieldPath: spec.parameters.fleetProject
      toFieldPath: spec.forProvider.clusterConfig.project
    - fromFieldPath: metadata.uid
      toFieldPath: spec.forProvider.clusterCredentials.secretRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-akscluster"

  - name: attachedCluster
    base:
      apiVersion: containerattached.gcp.gke.cloud.google.com/v1beta1
      kind: Cluster
      metadata:
        name: attachedcluster
      spec:
        forProvider:
          distribution: "aks"
          location: us-east4
          fleet:
          - project: "project/<project-number>"
    patches:
    - fromFieldPath: spec.parameters.k8sVersion
      toFieldPath: spec.forProvider.platformVersion
      transforms:
      - type: map
        map:
          1.24: 1.24.0-gke.4
          1.25: 1.25.0-gke.4
          1.26: 1.26.0-gke.2
    - fromFieldPath: status.odicIssuerUrl
      toFieldPath: spec.forProvider.oidcConfig[0].issuerUrl
    - fromFieldPath: spec.parameters.anthosGCPRegion
      toFieldPath: spec.forProvider.location
    - fromFieldPath: spec.parameters.fleetProject
      toFieldPath: spec.forProvider.fleet[0].project
      transforms:
      - type: string
        string:
          fmt: "projects/%s"
    - fromFieldPath: spec.parameters.adminUsers
      toFieldPath: spec.forProvider.authorization[0].adminUsers
    - fromFieldPath: status.clusterName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
